model:
#  model_architecture_file_path: "/work/scratch/dziuba/repos/ma_code/cfg/model_example.yaml"
  model_architecture:
#    model_architecture_origin: torchvision
#    model_architecture_name: deeplabv3_resnet50
    model_architecture_origin: segmentation_models_pytorch
    model_architecture_name: unet_inceptionresnetv2
    pretrained: True
    embedding_dims: 150
  channels: 3
  output_creation:  # first list element will be used to create the panoptic output prediction
#    - multi_sphere_association:
#        cat_id_radius_order_map_list: [ 7, 8, 11, 12, 13, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 31, 32, 33 ] #describes the mapping of the semantic class to the order of hyperspheres - from small hypersphere to big or regarding to index
#        radius_diff_dist: 0.1        # difference to next class association radius
#        radius_start_val: 0.1           # start radius value
#        radius_association_margin: 0.05  # max deviation from radius to still associate to closest radius
#        instance_clustering_method:
#          identity: {} # no args specified
#    - sphere_coords:
#        mean_origin: False
#
    - nearest_class_mean_association:
        instance_clustering_method:
          identity: { } # no args specified
#     - multi_sphere_association_flexible:
#        radius: 1
#        radius_association_margin: 0.5  # max deviation from radius to still associate to closest radius
#        instance_clustering_method:
#          identity: { } # no args specified
    - radius:
        mean_origin: False


optimizer:
  adam:
    lr: 0.001
    eps: 0.00000001
    weight_decay: 0
    warmup:
      start_lr: 0.00001
      end_lr: 0.001
      num_steps: 2500

scheduler:
  reduce_on_plateau:
    eps: 0.00000001
    factor: 0.1
    patience: 10
    threshold: 0.0001
    cooldown: 20

training:
  save_path: "/work/scratch/dziuba/ma_code_runs/trainings/debug12"
#  gpu_ids: [0]
  save_freq: 10
  metrics_calc_freq: 10
  num_epochs: 130
  use_cpp: False
  AMP: False
  compile: False
  best_eval_mode: "min"
  embedding_handler:
    storage_step_update_sample_size: 1     #per class base
    embedding_storage:
      memory_bank:
        num_embeddings: 500 # equally distributed to categories
    embedding_sampler:
      batch_sampler: {}

loss:
  train_loss:
    spherical_contrast_panoptic_means:
      sphere_ct_contr_loss:
        info_nce: {}
      num_pos_embeddings: 1
      loss_radius:
        mse: {}
      radius: 0.01
      cosine_emb_loss_margin: 0
      sphere_ct_contr_loss_weight: 1
      radius_loss_weight: 1
      similarity_loss_weight: 1

  val_loss:
    spherical_contrast_panoptic_means:
      sphere_ct_contr_loss:
        info_nce: { }
      num_pos_embeddings: 1
      loss_radius:
        mse: { }
      radius: 0.01
      cosine_emb_loss_margin: 0
      sphere_ct_contr_loss_weight: 1
      radius_loss_weight: 1
      similarity_loss_weight: 1
  metrics:
    - panoptic_quality:
        filter: None

#  metrics_file_path: "/work/scratch/dziuba/repos/ma_code/cfg/metrics_master.yaml"


data:
  datasets_file_path: "/work/scratch/dziuba/repos/ma_code/cfg/datasets_ref_debug_bigger.yaml"
  batch_size: 4
  num_workers: 0
  prefetch_factor: 4 # currently deprecated/not used
  img_width: 512
  img_height: 256
  load_ram: False # loads data fully into the main memory
  augmentations_file_path: "/work/scratch/dziuba/repos/ma_code/cfg/augmentations_base.yaml"

logging:
  name: "LOG"
  save_path: "/work/scratch/dziuba/ma_code_runs/logs/debug12"
  num_log_img: 5
  log_graph: False
  wandb_config:
    project: "MA"
    entity: "ma_dziuba"
  sampler:
    nthstep:
      step_size: [15, 15]


#  img_log_freq: 10 # set by metrics_calc_freq
#  num_log_img: 5


