model:
#  model_architecture_file_path: "/work/scratch/dziuba/repos/ma_code/cfg/model_example.yaml"
  model_architecture:
#    model_architecture_origin: torchvision
#    model_architecture_name: deeplabv3_resnet50
    model_architecture_origin: segmentation_models_pytorch
    model_architecture_name: unet_inceptionresnetv2
#    model_architecture_origin: mmseg
#    model_architecture_name: ocrnet-r101-d8-cityscapes
    pretrained: True
    embedding_dims: 50
  channels: 3
  output_creation:  # first list element will be used to create the panoptic output prediction
#    - multi_sphere_association:
#        cat_id_radius_order_map_list: [ 7, 8, 11, 12, 13, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 31, 32, 33 ] #describes the mapping of the semantic class to the order of hyperspheres - from small hypersphere to big or regarding to index
#        radius_diff_dist: 0.1        # difference to next class association radius
#        radius_start_val: 0.1           # start radius value
#        radius_association_margin: 0.05  # max deviation from radius to still associate to closest radius
#        instance_clustering_method:
#          identity: {} # no args specified
#    - sphere_coords:
#        mean_origin: False
#
    - nearest_class_mean_association:
        instance_clustering_method:
          identity: { } # no args specified
#          cuml_hdbscan:
#            min_samples: 4
#     - multi_sphere_association_flexible:
#        radius: 1
#        radius_association_margin: 0.5  # max deviation from radius to still associate to closest radius
#        instance_clustering_method:
#          identity: { } # no args specified
    - radius:
        mean_origin: False


optimizer:
  adam:
    lr: 0.001
    eps: 0.00000001
    weight_decay: 0
    warmup:
      start_lr: 0.00001
      end_lr: 0.001
      num_steps: 2500

scheduler:
  reduce_on_plateau:
    eps: 0.00000001
    factor: 0.1
    patience: 10
    threshold: 0.0001
    cooldown: 20

training:
  save_path: "/work/scratch/dziuba/ma_code_runs/trainings/angular_loss_debug"
#  gpu_ids: [0]
  save_freq: 10
  metrics_calc_freq: 10
  num_epochs: 150
  use_cpp: False
  AMP: False
  compile: False
  best_eval_mode: "min"
  cuml_mem_alloc: 2000000000 # in MB?
  embedding_handler: # remove part if necessary for training
    storage_step_update_sample_size: 1     #per class base
    embedding_storage:
      memory_bank:
        num_embeddings: 500 # equally distributed to categories
    embedding_sampler:
      batch_sampler: {}

loss:
  train_loss:
    metric_learning_sem_segm:
      class_metric_loss:
        contrastive_loss:
          pos_margin: 0
          neg_margin: 1
  val_loss:
    metric_learning_sem_segm:
      class_metric_loss:
        contrastive_loss:
          pos_margin: 0
          neg_margin: 1
  metrics:
    - panoptic_quality:
        filter: None

#  metrics_file_path: "/work/scratch/dziuba/repos/ma_code/cfg/metrics_master.yaml"


data:
  datasets_file_path: "/work/scratch/dziuba/repos/ma_code/cfg/datasets_ref_debug.yaml"
  batch_size: 1
  num_workers: 2
  prefetch_factor: 4 # currently deprecated
  img_width: 64
  img_height: 64
  load_ram: False # loads data fully into the main memory
  load_orig_size: True
  augmentations_file_path: "/work/scratch/dziuba/repos/ma_code/cfg/augmentations_crop.yaml"

logging:
  name: "LOG"
  save_path: "/work/scratch/dziuba/ma_code_runs/logs/angular_loss_debug"
  num_log_img: 5
  log_graph: False
  wandb_config:
    project: "MA"
    entity: "ma_dziuba"
  sampler:
    nthstep:
      step_size: [15, 15]


#  img_log_freq: 10 # set by metrics_calc_freq
#  num_log_img: 5


